### ISSUE TITLE
Downloaded 0 posts

### ISSUE THREAD

**Issue by mizzunet** [anteprandium/news2kindle#2]
I used default feeds.txt URLs for testing purpose, but every time it returns mothing downloaded.

INFO:root:Collecting posts since 2021-03-24 09:44:00.481873+00:00
INFO:root:Downloaded 0 posts
INFO:root:Finished.

**Comment by anteprandium** [comment]
Just to be clear, you know you need to change the timestamp of the feeds.txt file, right? It uses the timestamp of said file to download feeds from that time up to "now". On unix you do something like `touch -t 202103231024 filename`

You only need to do this for the first time; it should update the timestamp by itself for the subsequent runs.

**Comment by mizzunet** [comment]
> Just to be clear, you know you need to change the timestamp of the feeds.txt file, right? It uses the timestamp of said file to download feeds from that time up to "now". On unix you do something like `touch -t 202103231024 filename`
> 
> You only need to do this for the first time; it should update the timestamp by itself for the subsequent runs.

I think I haven't get you what you said, feeds.txt should include links RSS line by line nothing else, right?
I didn't get what you said about time stamps.
For example, Google blog RSS feeds.txt should be aa follows, right?
https://www.blog.google/rss/

**Comment by mizzunet** [comment]
Oh now I'm getting it, so if I need to download all feeds after 2021-03-24 10:24AM, I should run touch -t 202103231024 feeds.txt for changing it's modifications date, right? Let me try it

**Comment by mizzunet** [comment]
Oh now I'm getting it, so if I onoy need to download feeds after 2021-03-24 10:24AM, I should run `touch -t 202103231024 feeds.txt` for changing it's modifications date, right? Let me try it

**Comment by anteprandium** [comment]
Every file on the filesystem has some kind of timestamp attached to it. This is usually the last modification time. That's one thing. The other thing is that to keep feeds.txt clean, I chose to use the modification time of feeds.txt for the start of the time period to download articles: the "since when to download articles", so to say.

We might argue that it wasn't a wise choice, and I would agree :) The point is: if you just edit or modify feeds.txt in some way,  you just reset the timestamp to now. Use the touch command to reset the clock backwards some time!

**Comment by mizzunet** [comment]
> Every file on the filesystem has some kind of timestamp attached to it. This is usually the last modification time. That's one thing. The other thing is that to keep feeds.txt clean, I chose to use the modification time of feeds.txt for the start of the time period to download articles: the "since when to download articles", so to say.
> 
> We might argue that it wasn't a wise choice, and I would agree :) The point is: if you just edit or modify feeds.txt in some way, you just reset the timestamp to now. Use the touch command to reset the clock backwards some time!

You're it I could overcame it, thank you :) Though it returns another error related to SMTP setup I guess,
                                                                                  `Generating MOBI index for a book                                                                                                     MOBI output written to /dailynews.mobi
Output saved to   /dailynews.mobi
INFO:root:Sending to kindle email
Traceback (most recent call last):
  File "src/news2kindle.py", line 210, in <module>
    do_one_round()
  File "src/news2kindle.py", line 195, in do_one_round
    send_mail(send_from=EMAIL_FROM,
  File "src/news2kindle.py", line 148, in send_mail
    smtp = smtplib.SMTP_SSL(EMAIL_SMTP, EMAIL_SMTP_PORT)
  File "/usr/local/lib/python3.8/smtplib.py", line 1032, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/local/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 337, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 1038, in _get_socket                                                                  new_socket = socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):`

Here's .env 
![Screenshot_20210324-233048_1_1](https://user-images.githubusercontent.com/10193999/112361221-2aef4000-8cf9-11eb-8934-a03d7736397b.png)

**Comment by anteprandium** [comment]
Ah! Gmail is very picky about its clients and will not let you use "simple" authentication. Try another mail provider; like gmx.com
